version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb_shopping
    command: mongod --auth
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: shopping-system
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - ./redis-data:/data

volumes:
  mongo-data:
  redis-data:
